-- Source of truth + simulation, per company.
--
-- playbook_facts is the structured knowledge the supervisor actually owns:
-- interviewed answers about their company, products, pricing, funnel, and
-- closing. A row with a NULL/empty answer is an OPEN GAP — a question the
-- system generated and still needs the supervisor to fill in. That is how the
-- system "asks to be told" about the business, and how it tracks what it does
-- not know yet.
--
-- The free-text playbooks.brief and playbook_assets uploads remain valid
-- sources; these facts sit alongside them as the structured, gap-tracked layer
-- that both the reply pipeline and the quality judge read.
CREATE TABLE IF NOT EXISTS playbook_facts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  category TEXT NOT NULL CHECK (category IN
    ('profile', 'product', 'pricing', 'faq', 'funnel', 'objection', 'closing')),
  question TEXT NOT NULL,
  answer TEXT,
  priority SMALLINT NOT NULL DEFAULT 2 CHECK (priority BETWEEN 1 AND 3),
  source TEXT NOT NULL DEFAULT 'interview'
    CHECK (source IN ('interview', 'manual', 'simulation')),
  updated_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- One row per (company, question) so re-running the interview updates an
-- existing question instead of asking it twice.
CREATE UNIQUE INDEX IF NOT EXISTS playbook_facts_company_question_idx
  ON playbook_facts (company_id, lower(question));

CREATE INDEX IF NOT EXISTS playbook_facts_company_category_idx
  ON playbook_facts (company_id, category, priority);

-- Reusable test scenarios the supervisor sets up once and replays.
CREATE TABLE IF NOT EXISTS simulation_scenarios (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  persona TEXT NOT NULL DEFAULT '',
  opening_message TEXT NOT NULL,
  goal TEXT NOT NULL DEFAULT '',
  created_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS simulation_scenarios_company_idx
  ON simulation_scenarios (company_id, created_at DESC);

-- A graded reply. mode 'ai' = generated by the reply pipeline; mode 'human' =
-- typed by an agent practising; mode 'review' = a real human reply pulled from
-- an actual conversation and graded after the fact.
CREATE TABLE IF NOT EXISTS simulation_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  scenario_id UUID REFERENCES simulation_scenarios(id) ON DELETE SET NULL,
  mode TEXT NOT NULL CHECK (mode IN ('ai', 'human', 'review')),
  chat_id TEXT,
  customer_message TEXT NOT NULL,
  reply TEXT NOT NULL,
  transcript JSONB NOT NULL DEFAULT '[]'::jsonb,
  scores JSONB NOT NULL DEFAULT '{}'::jsonb,
  model TEXT,
  created_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS simulation_runs_company_idx
  ON simulation_runs (company_id, created_at DESC);
