-- Who actually wrote each outgoing reply.
--
-- Until now nothing recorded whether a message that went out to a customer was
-- typed by an agent or generated by the AI: sendReceipts is an in-memory
-- idempotency cache with a 5-minute TTL, and there is no message table. That
-- makes "review the quality of human replies" impossible after the fact — you
-- cannot grade an agent's work if you cannot tell which replies were theirs.
--
-- in_reply_to is the customer message being answered, captured best-effort at
-- send time so the quality judge has the context it needs. It may be NULL for
-- replies sent before this shipped, or when the inbound message is not in the
-- process cache (e.g. first reply after a restart).
CREATE TABLE IF NOT EXISTS outbound_replies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  chat_id TEXT NOT NULL,
  message_id TEXT,
  author TEXT NOT NULL CHECK (author IN ('ai', 'human')),
  author_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  body TEXT NOT NULL,
  in_reply_to TEXT,
  review_run_id UUID REFERENCES simulation_runs(id) ON DELETE SET NULL,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS outbound_replies_company_idx
  ON outbound_replies (company_id, author, created_at DESC);

-- The review queue: human replies nobody has graded yet.
CREATE INDEX IF NOT EXISTS outbound_replies_unreviewed_idx
  ON outbound_replies (company_id, created_at DESC)
  WHERE author = 'human' AND reviewed_at IS NULL;
